
[character]
success_symbol = "[‚Üí](bg:#0000cd fg:#ff1493)"
error_symbol = "[‚Üê](bg:#00ff00 fg:#4b0082)"


[cmd_duration]
min_time = 60_000
show_notifications = true
min_time_to_notify = 60_000

[directory]
truncation_length = 10
truncate_to_repo = false
style = "bold bright-cyan"

[git_branch]
style = "bold bright-purple"
symbol = "üå±  "


[username]
style_user = "bold bright-white"
style_root = "bold white"
format = "[$user]($style) in "
show_always = true



# language-specific settings
[python]

[rust]

